spring:
  application:
    name: optiplant

app:
  mailtrap:
    token: "aae51cae7dae2428a4ff4fa9697559be"
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
