spring:
  application:
    name: optiplant
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: my-username
    password: my-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
